#! /bin/sh

# Autostart
killall sxhkd; sxhkd -m 1 &
killall polybar; polybar top &

redshift -P -O 3500 &
dunst &
feh --randomize --bg-fill ~/Pictures/Wallpapers/* &

xrandr --auto
if xrandr -q | grep 'HDMI-1 connected'; then
	xrandr --output HDMI-1 --scale-from 1366x768 --same-as eDP-1
fi

# Monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Appearance
bspc config focused_border_color "#ba8baf"
bspc config active_border_color "#86c1b9"
bspc config normal_border_color "#585858"

bspc config border_width 2
bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config split_ratio 0.52
bspc config window_gap 10

# Rules
bspc rule -a firefox desktop=3
bspc rule -a discord desktop=5
