#! /bin/sh

# Autostart
sxhkd -m 1 &
killall dunst; dunst &
killall polybar; polybar -r top &
feh --bg-scale $HOME/Pictures/Wallpaper/skull.jpg &
xrandr --auto &
discord --start-minimized &
nm-applet &
redshift &

# Node & monitor
bspc monitor -d I II III IV V VI VII VIII IX X

# Appearence
bspc config focused_border_color "#458588"
bspc config normal_border_color "#3c3836"
bspc config active_border_color "#3c3836"

bspc config border_width 3
bspc config window_gap 0

bspc config borderless_monocle true
bspc config gapless_monocle false

bspc config split_ratio 0.52

# Rules
bspc rule -a discord desktop='^5'
bspc rule -a Pavucontrol desktop='^4' follow=on
bspc rule -a firefox desktop='^3'
