#! /bin/sh

# Autostart
sxhkd -m 1 &
killall dunst; dunst &
killall polybar; polybar -r top &
feh --bg-scale $HOME/Pictures/Wallpaper/gruvbox.png &
discord --start-minimized &
nm-applet &
killall redshift; redshift -P -O 3500 &

# monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Appearence
bspc config focused_border_color "#458588"
bspc config normal_border_color "#3c3836"
bspc config active_border_color "#3c3836"

bspc config border_width 3
bspc config borderless_monocle true
bspc config split_ratio 0.52
bspc config window_gap 0

# Rules
bspc rule -a discord desktop=5 focus=off follow=off
bspc rule -a Pavucontrol desktop=4 follow=on
bspc rule -a firefox desktop=3
